data:
  train_path: [/Users/eric/desktop/dl/data/accent_detection/labels/TRAIN_mozilla.csv]
  val_path: [/Users/eric/desktop/dl/data/accent_detection/labels/VAL_mozilla.csv]
  test_path: [/Users/eric/desktop/dl/data/accent_detection/labels/TEST_mozilla.csv]

log_dir: /Users/eric/Desktop/DL/Capstone/accent_detection_logs

dataloader:
  batch_size: 212
  num_workers: 2

pl_trainer:
  max_epochs: 500
  accelerator: mps

checkpoint_path: None