data:
  language_detection:
    train_path: [/media/capstone/HDD3/data/language_detection/labels/TRAIN_mozilla.csv]
    val_path: [/media/capstone/HDD3/data/language_detection/labels/VAL_mozilla.csv]
    test_path: [/media/capstone/HDD3/data/language_detection/labels/TEST_mozilla.csv]
  accent_detection:
    train_path: [/media/capstone/HDD3/data/accent_detection/labels/TRAIN_mozilla.csv]
    val_path: [/media/capstone/HDD3/data/accent_detection/labels/VAL_mozilla.csv]
    test_path: [/media/capstone/HDD3/data/accent_detection/labels/TEST_mozilla.csv]

log_dir:
  language_detection: /home/capstone/Desktop/Krisp/Capstone/language_logs
  accent_detection: /home/capstone/Desktop/Krisp/Capstone/accent_logs

dataloader:
  batch_size: 212
  num_workers: 2

pl_trainer:
  max_epochs: 500
  accelerator: mps

checkpoint_path: None

learning_rate: 10e-1

model_config_path: "./configs/model/net.yaml"
