sr: 16000
# language_detection, accent_detection
task: language_detection
data:
  language_detection:
    train_path: [
                 /media/capstone/HDD2/data/labels/Train_mozilla.csv,
                /media/capstone/HDD2/data/labels/Train_musan.csv
    ]
    val_path: [
               /media/capstone/HDD2/data/labels/Dev_mozilla.csv,
              /media/capstone/HDD2/data/labels/Dev_musan.csv
    ]
    test_path: [
                /media/capstone/HDD2/data/labels/Test_mozilla.csv,
               /media/capstone/HDD2/data/labels/Test_musan.csv
    ]

  accent_detection:
    train_path: [
                  /media/capstone/HDD2/data/labels/Train_mozilla.csv,
                 /media/capstone/HDD2/data/labels/Train_accentdb.csv,
                /media/capstone/HDD2/data/labels/Train_nptel.csv,
               /media/capstone/HDD2/data/labels/Train_musan.csv
    ]
    val_path: [
                /media/capstone/HDD2/data/labels/Dev_mozilla.csv,
               /media/capstone/HDD2/data/labels/Dev_accentdb.csv,
              /media/capstone/HDD2/data/labels/Dev_nptel.csv,
             /media/capstone/HDD2/data/labels/Dev_musan.csv
    ]
    test_path: [
                /media/capstone/HDD2/data/labels/Test_mozilla.csv,
               /media/capstone/HDD2/data/labels/Test_accentdb.csv,
              /media/capstone/HDD2/data/labels/Test_nptel.csv,
             /media/capstone/HDD2/data/labels/Test_musan.csv
    ]

log_dir:
  language_detection: /home/capstone/Desktop/Krisp/Capstone/exp
  accent_detection: /home/capstone/Desktop/Krisp/Capstone/accent_logs

dataloader:
  batch_size: 10
  num_workers: 10

pl_trainer:
  max_epochs: 500
  devices: 1
  accelerator: gpu
  limit_train_batches: 100
  limit_val_batches: 50
  val_check_interval: 0.2
  log_every_n_steps: 10

checkpoint_path: None

learning_rate: 0.001

model_config_path: ./configs/model/net.yaml

audio_processor:
    n_mels: 80
    n_fft: 512
    win_length: 0.025
    hop_length: 0.01

encodings:
  language_detection:
    en: 0 # english
    fr: 1 # french
    de: 2 # german
    es: 3 # spanish
    ca: 4 # catalan
    be: 5 # belarusian

    # other labels
    it: 6 # italian
    el: 6 # greek
    hy-AM: 6 # armenian
    Other: 7 # Noise

  accent_detection:
    # Mozilla
    United States English: 0
    England English: 1
    India and South Asia (India, Pakistan, Sri Lanka): 2
    Canadian English: 3
    Australian English: 4
    German English,Non native speaker: 5

    # accentdb
    american: 0
    british: 1
    indian: 2
    australian: 4

    Other: 6
#    indian: 2
