sr: 16000
task: language_detection
data:
  language_detection:
    train_path: [/media/capstone/HDD3/data/labels/TRAIN_mozilla_filtered.csv]
    val_path: [/media/capstone/HDD3/data/labels/DEV_mozilla.csv]
    test_path: [/media/capstone/HDD3/data/labels/TEST_mozilla_filtered.csv]
  accent_detection:
    train_path: [/media/capstone/HDD3/data/labels/TRAIN_mozilla.csv]
    val_path: [/media/capstone/HDD3/data/labels/VAL_mozilla.csv]
    test_path: [/media/capstone/HDD3/data/labels/TEST_mozilla.csv]

log_dir:
  language_detection: /home/capstone/Desktop/Krisp/Capstone/language_logs
  accent_detection: /home/capstone/Desktop/Krisp/Capstone/accent_logs

dataloader:
  batch_size: 10
  num_workers: 10

pl_trainer:
  max_epochs: 500
  devices: 1
  accelerator: gpu

checkpoint_path: None

learning_rate: 0.001

model_config_path: ./configs/model/net.yaml

audio_processor:
    n_mels: 80
    n_fft: 512
    win_length: 0.025
    hop_length: 0.01

encodings:
  language_detection:
    en: 0 # english
    fr: 1 # french
    de: 2 # german
    es: 3 # spanish
    ca: 4 # catalan
    be: 5 # belarusian
    it: 6 # italian
    hy-AM: 6 # armenian
    ru: 6 # russia
  accent_detection:
    usa: 0
    british: 1
