data:
  train_path: []
  val_path: []
  test_path: []

log_dir: /Users/eric/Desktop/DL/Capstone/accent_detection_logs

dataloader:
  batch_size: 212
  num_workers: 2

pl_trainer:
  max_epochs: 500
  accelerator: mps