- name: NormalizedMelSpectogram
  params:
    n_mels: 80
    window_fn: torch.hann_window
    n_fft: 512
    win_length: 16000*0.025
    hop_length: 16000*0.01

- name: ConvBatchNormRelu
  params:
    input_size: 80
    kernel_size: 33
    output_size: 256

- name: BBlock
  params:
    input_size: 256
    kernel_size: 33
    output_size: 256
    repeat: 2

- name: BBlock
  params:
    input_size: 256
    kernel_size: 39
    output_size: 256
    repeat: 2

- name: BBlock
  params:
    input_size: 256
    kernel_size: 51
    output_size: 512
    repeat: 2

- name: BBlock
  params:
    input_size: 512
    kernel_size: 63
    output_size: 512
    repeat: 2

- name: BBlock
  params:
    input_size: 512
    kernel_size: 75
    output_size: 512
    repeat: 2

- name: ConvBatchNormRelu
  params:
    input_size: 512
    kernel_size: 1
    output_size: 1500

- name: StatsPooling
  params: {}

- name: Linear
  params:
    in_features: 3000
    out_features: 512

- name: BatchNorm1d
  params:
    num_features: 512

- name: Linear
  params:
    in_features: 512
    out_features: 7