samplerate: 16000
duration: 5
target_dir: /media/capstone/HDD2/data

datasets:
  MozillaCV:
    source_path: /media/capstone/HDD2/source_data/MozillaCV
  Musan:
    source_path: /media/capstone/HDD3/source_data/musan
  AccentDB:
    source_path: /media/capstone/HDD2/source_data/AccentDB
  Nptel:
    source_path: /media/capstone/HDD2/source_data/NPTEL

datasets_to_process: [MozillaCV]

# language_detection, accent_detection
task: language_detection

# en, es, de, fr, be, ca, el, it, hy-AM
languages: [hy-AM]

accents: [en, indian]

convert:
  need_to_convert: False
  datasets_to_convert: [MozillaCV]
  wav: True

voices_path: '/home/capstone/Desktop/Krisp/source_data/voices'

