samplerate: 16000
duration: 5
target_dir: /media/capstone/HDD3/data

datasets:
  MozillaCV:
    source_path: /media/capstone/HDD3/source_data/MozillaCV
  Musan:
    source_path: /media/capstone/HDD3/source_data/musan
  datasets_to_process: [Musan]

datasets_to_process: [Musan]

# language_detection, accent_detection
task: language_detection

# en, es, de, fr, be, ca, el, it, pt, ru, hy-AM
languages: [el, it, pt, ru, hy-AM]

accents: [en, indian]

convert:
  need_to_convert: True
  datasets_to_convert: [MozillaCV]
  wav: True
